# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-staging.yml
#
#
# URL of static site
url: "https://staging.trustedfirmware.org"
# Destination folder
destination: staging.trustedfirmware.org
# Production boolean used in layouts / includes
production: false
# Google Analytics
google_analytics:
  enabled: false
  code: GTM-TKVP3S4
