# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-production.yml
#
#
# URL of static site
url: "https://www.trustedfirmware.org"
# Destination folder
destination: production.trustedfirmware.org
# Production boolean used in layouts / includes
production: true